### ISSUE TITLE
[feature] add warning for unusual modes or remove them completly

### ISSUE THREAD

**Issue by mcm1957** [AlCalzone/create-adapter#1088]
I suggestto add some warning for unusal mode selections,

I just spent 3h searching with a dev why his new adpter runs without problmes with dev-server but simply does not start when installed iwthout any useful message,

The reason was that mode was set to subscribe (instead of deamon or scheduled)....

So I suggest to either:
- remove all modes besides daemon and scheduled from creator selection as other modes are likely to used be experienced devs only
- or to output a big warning if other modes are selected

A normal beginner cannot know the reults of i.e. once, subcribe ect (I even die not know f subscribe until now :-)

**Comment by AlCalzone** [comment]
We already say that `deamon` is recommended for most adapters. I wouldn't like to remove options since if they are not available, even experienced devs might not even know they are possible.

Suggestion:
- move `schedule` to the 2nd place in the list
- put a hint behind the others: `(only choose if you know what you're doing)` or so

Little side swipe:
I considered copying the question, keeping only `daemon/schedule` for non-expert mode and all options for expert mode... But then I noticed that this entire question is already expert-mode only. So it sounds like the dev enabled expert mode, then didn't read the hint next to `daemon` and then selected an option they didn't understand 🤷‍♂️

**Comment by mcm1957** [comment]
Well - the option subscribe was not even wellknown to Foxriver :-)

But OK, I can life with an aditional hint too. 

In regards to expert mode - the only question I know is whether you want to be asked everything or only th emost important things. Thats not related to expert/non-expert in my opinion.

**Comment by AlCalzone** [comment]
> the option schedule was not even wellknown to Foxriver

Really?! We have quite some schedule adapters.

> Thats not related to expert/non-expert in my opinion.

Ok then maybe also add a hint there that it's meant for experts.

**Comment by mcm1957** [comment]
> > the option schedule was not even wellknown to Foxriver
> 
> Really?! We have quite some schedule adapters.

Sorry - typo. Should read SUBCRIBE (I corrected last post)

schedule and deamon are widely used (I guess 99% of adapters)

> Ok then maybe also add a hint there that it's meant for experts.

Cant comment - I never tried without "Ask me all". I do not know what questions will be omitted then.
