### ISSUE TITLE
Remove nodejs 12.x from adapter tests (EOL) and add 18.x

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/create-adapter#906]
https://github.com/ioBroker/create-adapter/blob/f82bffb5f86889e7c7f51298f137654007945c34/templates/_github/workflows/test-and-release.yml.ts#L18

**Comment by Apollon77** [comment]
And add Nodejs 18 ? :-)

**Comment by AlCalzone** [comment]
Has ioBroker officially dropped support for Node 12?

**Comment by klein0r** [comment]
Even if ioBroker hasn't dropped nodejs 12 support officially - why should new adapters support/test a version which is EOL?

**Comment by AlCalzone** [comment]
I agree, but AFAIK the last time we waited to do this by default until the stable js-controller no longer supported the old Node.js version.
@Apollon77 ?

**Comment by klein0r** [comment]
So maybe we should wait for js-controller 4.1.0 ? 

https://github.com/ioBroker/ioBroker.js-controller/issues/1910

**Comment by klein0r** [comment]
At the moment the js-controller dependency for a new adapter is 2.0.0.

https://github.com/ioBroker/create-adapter/blob/f82bffb5f86889e7c7f51298f137654007945c34/templates/io-package.json.ts#L113

js-controller 2.0.0 has nodejs >=8.0.0 as a requirement. The question is, why should we keep the EOL version 12.x?

If the argument is, that the js-controller hasn't dropped support for that version, we should also add 10.x and 8.x to the tests (because new adapters can also run with js-controller 2.0.0).

I thought, 10.x and 8.x have been removed, because they are EOL.

If the current list is defined as "all nodejs versions which are supported by the latest stable release of js-controller" we can close this issue 😄

**Comment by AlCalzone** [comment]
The minimum required versions here are usually selected by functional requirements, e.g. some things used in the template were first supported in js-controller 2.0.0. Unnecessarily increasing the minimum required versions means that adapters won't be allowed to run on existing systems, even if they would run just fine.

I'm fine with limiting tests to the 14/16/18.x range, but I don't think we need to artificially limit the supported versions, EOL or not.

Recommending users to upgrade is one thing, actually preventing them from running these versions just because they aren't officially supported, is another. FWIW, I do have some production systems still running on Node.js 6 somewhere.

**Comment by Apollon77** [comment]
Additionally the 2.0.0 depenedency to controller just comes from the fact that adapter-core requires this ... So there is even no relation to node.js from this dependency ...
